name: PiskoClicker
version: ${project.version}
main: com.gay.piskoclicker.PiskoClicker
authors: [oofxFrozen]
description: CLICK ON DICKS AND EARN MONEY
commands:
  money:
    description: Check your current amount of dicks!
    usage: /money
  top:
    description: Shows top of players.
    usage: /top
  mytime:
    description: Get your played time!
    usage: /mytime
permissions:
  admin.*:
    description: Admin perms
    default: op

